import { type NextPage } from "next";
import Head from "next/head";

import { trpc } from "../utils/trpc";

const Home: NextPage = () => {
  const dances = trpc.dances.getAll.useQuery();

  if (!dances.data) {
    return <div> Data is loading</div>;
  }

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>
        {dances.data.map((dance) => (
          <>
            <div>{dance.comment}</div>
            <div>{dance.timestamp}</div>
            <div>{dance.name}</div>
            <div>{dance.url}</div>
          </>
        ))}
      </div>
    </>
  );
};

export default Home;
