import { defaultContext } from "@tanstack/react-query";
import { type NextPage } from "next";
import Head from "next/head";
import DanceCard from "../components/DanceCard";

import { trpc } from "../utils/trpc";

const Home: NextPage = () => {
  const dances = trpc.dances.getAll.useQuery();

  if (!dances.data) {
    return <div> Data is loading</div>;
  }

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div >
        {dances.data.map((dance) => (
          <DanceCard
            key={dance.id}
            url={dance.url}
            name={dance.name}
            timestamp={dance.timestamp}
            comment={dance.comment}
          />
        ))}
      </div>
    </>
  );
};

export default Home;
